### ISSUE TITLE
Physical arrow keys not working as MO/TO arrows

### ISSUE THREAD

**Issue by Galious** [Zlika/theodore#11] opened 2019-02-16 11:36 UTC
Hello,
Under Retroarch 1.7.5 on Windows 10 x64, with Theodore core v. fee726b, I cannot have the physical arrow keys from my keyboard working as MO/TO arrow keys.

Under MO/TO Basic, these keys input the characters "2", "4", "6", "8" instead of moving the cursor (as if they were the arrow keys from the numerical keypad).

I made sure to use "Enable hotkeys" hotkey in Retroarch, disabled the Retropad, and also used the "Game focus toggle" hotkey to disable all other hotkeys, but the behavior remains the same.

This is a blocking issue for games like "L'Aigle d'Or", which can only be played with the keyboard.

This issue is not present on DCMO5 v6.8 (used via Dosbox).

**Comment by Zlika** [comment] 2019-02-16 15:13
Hi!
Thanks for the bug report, I will have a look at it. Does the problem occurs in both MO5 and TO8 modes? I remember testing l'aigle d'or in TO8 mode with the keyboard and it was working, but maybe the arrow keys were emulating the joystick.

**Comment by Galious** [comment] 2019-02-16 16:46
Yes it occurs in both modes and can be seen in the Basic environment, where the arrow keys generate digits.

I don't think I left a wrong setting in Retroarch, as the keyboard arrow keys are working correctly in the Microsoft Basic environment of the BlueMSX core (they control the cursor correctly).

By the way, in TO8 mode, after entering the first Basic option (1), I cannot type a double quote character (required for RUN").
The "2" key on the keyboard always inputs a "2", even with shift pressed. This issue is not present in MO5 mode, where I manage to type a double quote by pressing shift + 2.

Regarding the joystick emulation, I did not manage to use a joystick with L'Aigle d'Or as a backup solution.
I managed to use one with La Mine aux Diamants, where the choice between keyboard and joystick is offered by the game, and in this case the game can be played, even if the keyboard control does not work due to the current issue.

**Comment by z3tof** [comment] 2019-02-16 17:08
In MO5 mode and in lastest recalbox beta, there is no problem : the arrow keys move the cursor.
And the game "L'aigle d'or" works fine.

**Comment by Zlika** [comment] 2019-02-16 21:02
Hi!
I fixed the problems with the number keys in TO mode.
However, for the arrow keys, I cannot reproduce the problem on Linux. I will try to do it on Windows, however if it is a Windows-specific problem it will be hard to fix for me because I don't have a Windows toolchain to build the core on it. Moreover, it may be a RetroArch bug (I already filled a bug on RA keyboard management on Windows, cf. https://github.com/libretro/RetroArch/issues/6971).

**Comment by Galious** [comment] 2019-02-16 21:13
Hi, thanks for all the quick answers.
I just tested the latest nightly Retroarch, and the arrow key issue has been solved !
It must have been corrected by a recent fix on Retroarch side (the current stable version is 1.7.6 and I had already upgraded to 1.7.5 not long ago).
Regarding the number keys fix, I will test it when it is available in the build bot repository, thanks !
And by the way, many thanks for having ported DCMOTO to Libretro, it is making MO5 emulation a lot simpler.

**Comment by Zlika** [comment] 2019-02-16 21:35
You're welcome.
I close the issue as I think it is solved. Feel free to reopen it if you think it should.

**Closed** 2019-02-16 21:35 UTC
Labels: bug

**Comment by Zlika** [comment] 2019-02-18 21:24
Following discussion with RetroArch developers about keyboard layouts and recent changes done on RetroArch 1.7.6 on this topic, I made major changes on the keyboard emulation that should fix all the problems (I still have to test these changes on Windows though).
